# Generated by Django 3.2.9 on 2021-12-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sequence',
            field=models.CharField(choices=[('shuffle', 'shuffle'), ('not shuffle', 'not shuffle')], default='not shuffle', max_length=50),
        ),
    ]
