# Generated by Django 3.2.9 on 2021-12-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_course_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.CharField(choices=[('iq', 'iq'), ('technical', 'technical')], default='technical', max_length=50),
        ),
    ]
