# Generated by Django 3.2.9 on 2021-12-21 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_course_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='section',
        ),
    ]
