# Generated by Django 3.2.9 on 2021-12-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_remove_course_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('iq', 'iq'), ('technical', 'tehcnical')], default='technical', max_length=50),
        ),
    ]
