# Generated by Django 3.2.9 on 2021-12-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.AddField(
            model_name='student',
            name='exam',
            field=models.CharField(choices=[('1', 'python'), ('2', 'java')], default=1, max_length=40),
        ),
    ]
