# Generated by Django 3.2.9 on 2021-12-20 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201209_2125'),
        ('student', '0003_auto_20211217_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.course'),
        ),
    ]
